[API]
port     = ":3306"
version  = "alpha"

[DB]
dbms = "mysql"
user = "root"
pass = "secret"
protocol = "tcp([localhost]:13306)"
dbname = "WorkTimeRecoder"

[BOT]
tokenID    ="xoxb-1015900425939-1027655437248-7oQMuN1zUmCr4uhVz2qHCFAP"
botID      = "<@U010TK9CV7A>"
channelID  = "C010HHPLTFB"
signupCh   = "C010JDA71BK"