[API]
port     = ":3306"
version  = "alpha"

[DB]
dbms = "mysql"
user = "root"
pass = "secret"
protocol = "tcp(WorkTimeRecoder-db)"
dbname = "WorkTimeRecoder"

[BOT]
tokenID    ="xoxb-1015900425939-1027655437248-YtVSnrQYfZ3NBSsx4nHIf3Du"
botID      = "<@U010TK9CV7A>"
workingCh  = "C010HHPLTFB"
reportCh   = "C011CNUDR43"
signupCh   = "C010JDA71BK"