[API]
port     = ":3306"
version  = "alpha"

[DB]
dbms = "mysql"
user = "root"
pass = "secret"
protocol = "tcp(WorkTimeRecoder-db)"
dbname = "WorkTimeRecoder"

[BOT]
tokenID    ="xoxb-"
botID      = "<@U010TK9CV7A>"
workingCh  = ""
reportCh   = ""
signupCh   = ""