version: "3"

services:
  go:
    restart: always
    build: ../server
    volumes:
      - ../server:/go/app
    working_dir: /go/app
    ports:
      - "49400:49400"
    container_name: "WorkTimeRecoder-server"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf:/etc/mysql/conf.d
      - ../mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: WorkTimeRecoder
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    ports:
      - "13306:3306"
    container_name: "WorkTimeRecoder-db"
